version: '3.8'

services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd1!
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - mysql_network

volumes:
  mysql_data:
    name: mysql_data

networks:
  mysql_network:
    name: mysql_network